### ISSUE TITLE
Prints help argument (-?) not work correctly.

### ISSUE THREAD

**Issue by MairwunNx** [wildscamp/FontManager#2]
If i launch your FontManager application with "-?" argument application run on 0.5 sec and close.

You need add Console.ReadKey(); to end printing info to console.

![issue](https://user-images.githubusercontent.com/39625750/48970835-562acd00-f022-11e8-8248-024b8998f2f9.gif)

**Comment by hjoelr** [comment]
@MairwunNx Adding a Console.ReadKey() when printing the help is not standard practice. Instead, you should run `FontMgr.exe -?` from an elevated command prompt. The command prompt will stay open after you run the command and you will be able to see the help.

**Comment by MairwunNx** [comment]
Lol, thanks, i don't know what it need run in console! I usually run it with lnk.
